import type { GrowthSeed, FateDie, SeedBodyStructure } from '@/types/growth';

/**
 * Canonical seed catalog — 48 seeds parsed from Character Creation Examples.csv
 * Seeds are the starting template for entity creation. Each defines base stats,
 * traits, skills, and a KRMA Value (KV) that represents creation cost.
 */

function fateDie(n: number): FateDie {
  const map: Record<number, FateDie> = { 4: 'd4', 6: 'd6', 8: 'd8', 12: 'd12', 20: 'd20' };
  return map[n] || 'd6';
}

function parseList(s: string): string[] {
  if (!s || s === 'None') return [];
  return s.split(',').map(x => x.trim()).filter(Boolean);
}

// Default humanoid body structure — used for most seeds until species-specific ones are defined
export const HUMANOID_BODY: SeedBodyStructure = {
  parts: [
    'HEAD', 'TORSO',
    'LEFT_UPPER_ARM', 'LEFT_LOWER_ARM',
    'RIGHT_UPPER_ARM', 'RIGHT_LOWER_ARM',
    'LEFT_UPPER_LEG', 'LEFT_LOWER_LEG',
    'RIGHT_UPPER_LEG', 'RIGHT_LOWER_LEG',
  ],
  vitals: ['HEAD', 'TORSO'],
};

export const SEED_CATALOG: GrowthSeed[] = [
  {
    name: 'Human',
    description: 'Humans are diverse and adaptable, originating from countless worlds across fantasy and sci-fi civilizations. Highly versatile and resourceful.',
    baseFateDie: fateDie(6),
    frequency: 40,
    fatedAge: 80,
    baseResist: 15,
    attributes: { clout: 5, celerity: 5, constitution: 5, focus: 7, flow: 5, willpower: 13, wisdom: 5, wit: 5 },
    skills: [],
    nectars: parseList('Ambitious'),
    thorns: parseList('Bounded Potential'),
    seedKV: 225, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Altered Human',
    description: 'Infinite variations/mutations of humans for those who want to be different than baseline.',
    baseFateDie: fateDie(6),
    frequency: 70,
    fatedAge: 85,
    baseResist: 15,
    attributes: { clout: 5, celerity: 5, constitution: 5, focus: 5, flow: 7, willpower: 13, wisdom: 5, wit: 5 },
    skills: [],
    nectars: parseList('May purchase Nectars with starting frequency'),
    thorns: parseList('May choose Thorns to increase Frequency'),
    seedKV: 350, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Elven',
    description: 'Graceful and long-lived, with enhanced magical affinity but reduced technological integration.',
    baseFateDie: fateDie(4),
    frequency: 30,
    fatedAge: 500,
    baseResist: 13,
    attributes: { clout: 5, celerity: 12, constitution: 8, focus: 6, flow: 14, willpower: 5, wisdom: 13, wit: 6 },
    skills: [],
    nectars: parseList('Dark Sight'),
    thorns: parseList('Long Lifespan Frailty'),
    seedKV: 255, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Dwarven',
    description: 'Hardy mountain dwellers with superior crafting abilities and enhanced durability.',
    baseFateDie: fateDie(6),
    frequency: 30,
    fatedAge: 350,
    baseResist: 18,
    attributes: { clout: 12, celerity: 5, constitution: 12, focus: 6, flow: 3, willpower: 8, wisdom: 5, wit: 8 },
    skills: [],
    nectars: parseList('Dark Sight'),
    thorns: parseList('Technological Dependency'),
    seedKV: 580, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Neo-Human',
    description: 'Post-human evolved beings with advanced technological integration but reduced baseline attributes.',
    baseFateDie: fateDie(8),
    frequency: 20,
    fatedAge: 200,
    baseResist: 15,
    attributes: { clout: 0, celerity: 0, constitution: 0, focus: 0, flow: 0, willpower: 0, wisdom: 0, wit: 0 },
    skills: [],
    nectars: parseList('Machine Interfacing, Strange Vibrations'),
    thorns: parseList('Tech Addiction'),
    seedKV: 1640, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Cambion',
    description: 'Half-demon hybrids with enhanced physical capabilities and inherent magical resistance.',
    baseFateDie: fateDie(6),
    frequency: 40,
    fatedAge: 150,
    baseResist: 16,
    attributes: { clout: 8, celerity: 10, constitution: 5, focus: 5, flow: 5, willpower: 10, wisdom: 5, wit: 5 },
    skills: [],
    nectars: parseList('Demonic Heritage'),
    thorns: parseList('Dual Nature'),
    seedKV: 280, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Argentum Sanguis',
    description: 'Ancient bloodline with powerful heritage but requiring custom balancing for each character.',
    baseFateDie: fateDie(8),
    frequency: 40,
    fatedAge: 300,
    baseResist: 12,
    attributes: { clout: 2, celerity: 2, constitution: 2, focus: 4, flow: 4, willpower: 6, wisdom: 5, wit: 4 },
    skills: [],
    nectars: parseList('Make One Custom'),
    thorns: parseList('Ancient Bloodline Curse'),
    seedKV: 1089, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Orcish',
    description: 'Brutal warrior-nomads with immense physical prowess but limited magical and technological aptitude.',
    baseFateDie: fateDie(6),
    frequency: 50,
    fatedAge: 60,
    baseResist: 20,
    attributes: { clout: 15, celerity: 8, constitution: 15, focus: 3, flow: 3, willpower: 12, wisdom: 3, wit: 3 },
    skills: parseList('Intimidation'),
    nectars: parseList('Berserker Rage'),
    thorns: parseList('Social Outcast'),
    seedKV: 315, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Halfling',
    description: 'Small folk with natural stealth abilities and remarkable luck in dire situations.',
    baseFateDie: fateDie(6),
    frequency: 60,
    fatedAge: 120,
    baseResist: 12,
    attributes: { clout: 3, celerity: 10, constitution: 3, focus: 8, flow: 8, willpower: 15, wisdom: 8, wit: 5 },
    skills: parseList('Stealth'),
    nectars: parseList('Lucky'),
    thorns: parseList('Small Stature'),
    seedKV: 170, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Goblinoid',
    description: 'Scrappy survivors who excel in groups and make the most of discarded resources.',
    baseFateDie: fateDie(4),
    frequency: 45,
    fatedAge: 45,
    baseResist: 14,
    attributes: { clout: 8, celerity: 12, constitution: 8, focus: 5, flow: 4, willpower: 6, wisdom: 4, wit: 8 },
    skills: parseList('Scavenging'),
    nectars: parseList('Pack Mentality'),
    thorns: parseList('Compulsive Behavior'),
    seedKV: 135, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Tiefling',
    description: 'Planetouched beings with devilish heritage granting supernatural resilience and cunning.',
    baseFateDie: fateDie(6),
    frequency: 35,
    fatedAge: 100,
    baseResist: 16,
    attributes: { clout: 6, celerity: 6, constitution: 6, focus: 8, flow: 8, willpower: 8, wisdom: 6, wit: 7 },
    skills: [],
    nectars: parseList('Infernal Resilience'),
    thorns: parseList('Cursed Bloodline'),
    seedKV: 220, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Fey-Touched',
    description: 'Mortals touched by fey magic, existing partially between worlds with enhanced magical sensitivity.',
    baseFateDie: fateDie(4),
    frequency: 25,
    fatedAge: 250,
    baseResist: 11,
    attributes: { clout: 3, celerity: 15, constitution: 4, focus: 12, flow: 15, willpower: 10, wisdom: 12, wit: 4 },
    skills: [],
    nectars: parseList('Otherworldly Grace'),
    thorns: parseList('Reality Disconnect'),
    seedKV: 140, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Astral Drifter',
    description: 'Beings who have spent eons drifting through astral space, gaining cosmic perspective but losing grounding.',
    baseFateDie: fateDie(8),
    frequency: 30,
    fatedAge: 1000,
    baseResist: 13,
    attributes: { clout: 4, celerity: 8, constitution: 6, focus: 10, flow: 6, willpower: 8, wisdom: 8, wit: 10 },
    skills: parseList('Navigation'),
    nectars: parseList('Void Walking'),
    thorns: parseList('Temporal Displacement'),
    seedKV: 935, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Crystalline',
    description: 'Silicon-based lifeforms with incredible durability but limited flexibility and mobility.',
    baseFateDie: fateDie(6),
    frequency: 20,
    fatedAge: 2000,
    baseResist: 25,
    attributes: { clout: 6, celerity: 3, constitution: 18, focus: 8, flow: 3, willpower: 12, wisdom: 6, wit: 3 },
    skills: [],
    nectars: parseList('Energy Absorption'),
    thorns: parseList('Brittle Form'),
    seedKV: 1060, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Shapeshifter',
    description: 'Natural polymorphs who can alter their appearance but struggle with consistent identity.',
    baseFateDie: fateDie(6),
    frequency: 45,
    fatedAge: 90,
    baseResist: 14,
    attributes: { clout: 8, celerity: 8, constitution: 8, focus: 6, flow: 6, willpower: 8, wisdom: 8, wit: 8 },
    skills: parseList('Deception'),
    nectars: parseList('Perfect Mimicry'),
    thorns: parseList('Identity Crisis'),
    seedKV: 215, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Undying',
    description: 'Beings who have transcended death through dark pacts or ancient curses.',
    baseFateDie: fateDie(4),
    frequency: 15,
    fatedAge: 5000,
    baseResist: 22,
    attributes: { clout: 5, celerity: 5, constitution: 12, focus: 8, flow: 5, willpower: 15, wisdom: 10, wit: 5 },
    skills: [],
    nectars: parseList('Deathless Vigor'),
    thorns: parseList('Unholy Aura'),
    seedKV: 3280, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Synthetic',
    description: 'Artificial beings created with advanced technology but limited emotional range.',
    baseFateDie: fateDie(8),
    frequency: 35,
    fatedAge: 500,
    baseResist: 18,
    attributes: { clout: 8, celerity: 8, constitution: 12, focus: 12, flow: 4, willpower: 6, wisdom: 4, wit: 12 },
    skills: parseList('Technical Skills'),
    nectars: parseList('Logical Processing'),
    thorns: parseList('Emotional Limitations'),
    seedKV: 3530, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Void-Born',
    description: 'Entities born in the spaces between realities, naturally resistant to cosmic forces.',
    baseFateDie: fateDie(4),
    frequency: 20,
    fatedAge: 400,
    baseResist: 19,
    attributes: { clout: 6, celerity: 6, constitution: 10, focus: 9, flow: 9, willpower: 12, wisdom: 9, wit: 6 },
    skills: [],
    nectars: parseList('Entropy Resistance'),
    thorns: parseList('Existential Dread'),
    seedKV: 950, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Elemental-Kin',
    description: 'Humanoids with elemental bloodlines granting natural magical affinity but environmental limitations.',
    baseFateDie: fateDie(6),
    frequency: 30,
    fatedAge: 200,
    baseResist: 16,
    attributes: { clout: 10, celerity: 6, constitution: 12, focus: 10, flow: 12, willpower: 6, wisdom: 8, wit: 4 },
    skills: parseList('Elemental Affinity'),
    nectars: parseList('Primal Connection'),
    thorns: parseList('Environmental Dependency'),
    seedKV: 295, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Celestial',
    description: 'Angelic beings operating in mortal realms with divine blessings but bound by celestial codes.',
    baseFateDie: fateDie(4),
    frequency: 25,
    fatedAge: 3000,
    baseResist: 17,
    attributes: { clout: 5, celerity: 8, constitution: 8, focus: 12, flow: 12, willpower: 18, wisdom: 15, wit: 7 },
    skills: [],
    nectars: parseList('Divine Favor'),
    thorns: parseList('Mortal Compassion'),
    seedKV: 490, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Abyssal-Spawn',
    description: 'Demon-touched beings with infernal strength but unpredictable and destructive tendencies.',
    baseFateDie: fateDie(6),
    frequency: 45,
    fatedAge: 250,
    baseResist: 18,
    attributes: { clout: 12, celerity: 10, constitution: 12, focus: 6, flow: 6, willpower: 8, wisdom: 4, wit: 6 },
    skills: parseList('Intimidation'),
    nectars: parseList('Hellish Resilience'),
    thorns: parseList('Chaotic Impulses'),
    seedKV: 540, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Psionic',
    description: 'Telepathic beings with powerful mental abilities but vulnerability to psychic feedback.',
    baseFateDie: fateDie(8),
    frequency: 25,
    fatedAge: 90,
    baseResist: 12,
    attributes: { clout: 3, celerity: 6, constitution: 3, focus: 15, flow: 8, willpower: 12, wisdom: 12, wit: 15 },
    skills: parseList('Mental Powers'),
    nectars: parseList('Psychic Sensitivity'),
    thorns: parseList('Mental Overload'),
    seedKV: 445, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Construct',
    description: 'Magical automatons with incredible durability and focus but limited emotional capacity.',
    baseFateDie: fateDie(6),
    frequency: 40,
    fatedAge: 1000,
    baseResist: 22,
    attributes: { clout: 12, celerity: 4, constitution: 16, focus: 10, flow: 2, willpower: 8, wisdom: 4, wit: 10 },
    skills: parseList('Technical Knowledge'),
    nectars: parseList('Tireless Function'),
    thorns: parseList('Emotional Void'),
    seedKV: 1670, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Time-Lost',
    description: 'Beings unstuck in time with knowledge of multiple timelines but unreliable temporal anchoring.',
    baseFateDie: fateDie(4),
    frequency: 20,
    fatedAge: 75,
    baseResist: 15,
    attributes: { clout: 6, celerity: 6, constitution: 6, focus: 8, flow: 8, willpower: 10, wisdom: 12, wit: 8 },
    skills: parseList('Temporal Lore'),
    nectars: parseList('Chrono-Perception'),
    thorns: parseList('Timeline Displacement'),
    seedKV: 245, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Dream-Walker',
    description: 'Entities who exist partially in the dream realm with enhanced imagination but weakened physical form.',
    baseFateDie: fateDie(6),
    frequency: 30,
    fatedAge: 60,
    baseResist: 10,
    attributes: { clout: 4, celerity: 8, constitution: 4, focus: 12, flow: 14, willpower: 8, wisdom: 14, wit: 8 },
    skills: parseList('Dream Lore'),
    nectars: parseList('Lucid Dreaming'),
    thorns: parseList('Reality Blur'),
    seedKV: 150, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Plague-Bearer',
    description: 'Survivors of cosmic plagues with enhanced immune systems but perpetual infection risk.',
    baseFateDie: fateDie(6),
    frequency: 50,
    fatedAge: 70,
    baseResist: 17,
    attributes: { clout: 8, celerity: 6, constitution: 14, focus: 5, flow: 5, willpower: 10, wisdom: 6, wit: 5 },
    skills: parseList('Disease Resistance'),
    nectars: parseList('Viral Adaptation'),
    thorns: parseList('Carrier Status'),
    seedKV: 535, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Starborn',
    description: 'Beings born in stellar nurseries with incredible cosmic attunement but dependence on stellar energy.',
    baseFateDie: fateDie(8),
    frequency: 15,
    fatedAge: 5000,
    baseResist: 20,
    attributes: { clout: 4, celerity: 4, constitution: 8, focus: 14, flow: 10, willpower: 10, wisdom: 14, wit: 12 },
    skills: parseList('Astral Navigation'),
    nectars: parseList('Cosmic Awareness'),
    thorns: parseList('Solar Dependency'),
    seedKV: 1360, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Machine-Hybrid',
    description: 'Cyborgs integrating organic and mechanical components with enhanced capabilities but technical dependencies.',
    baseFateDie: fateDie(6),
    frequency: 35,
    fatedAge: 150,
    baseResist: 19,
    attributes: { clout: 10, celerity: 8, constitution: 12, focus: 8, flow: 6, willpower: 8, wisdom: 6, wit: 14 },
    skills: parseList('Technical Interface'),
    nectars: parseList('Cybernetic Enhancement'),
    thorns: parseList('System Vulnerability'),
    seedKV: 3700, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Quantum-Phased',
    description: 'Beings existing in quantum superposition with reality-bending abilities but unstable existence.',
    baseFateDie: fateDie(8),
    frequency: 20,
    fatedAge: 100,
    baseResist: 14,
    attributes: { clout: 6, celerity: 12, constitution: 6, focus: 12, flow: 8, willpower: 8, wisdom: 10, wit: 12 },
    skills: parseList('Phase Shifting'),
    nectars: parseList('Quantum Entanglement'),
    thorns: parseList('Probability Cascade'),
    seedKV: 1170, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Soul-Forged',
    description: 'Warriors whose souls have been reforged in spiritual fires, granting power but fragmenting identity.',
    baseFateDie: fateDie(4),
    frequency: 25,
    fatedAge: 300,
    baseResist: 21,
    attributes: { clout: 8, celerity: 6, constitution: 14, focus: 6, flow: 12, willpower: 14, wisdom: 10, wit: 6 },
    skills: [],
    nectars: parseList('Spirit Weapon'),
    thorns: parseList('Soul Fragments'),
    seedKV: 960, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Echo-Being',
    description: 'Reflections of other beings given independent existence with balanced abilities but derivative nature.',
    baseFateDie: fateDie(6),
    frequency: 30,
    fatedAge: 80,
    baseResist: 13,
    attributes: { clout: 7, celerity: 7, constitution: 7, focus: 7, flow: 7, willpower: 7, wisdom: 7, wit: 7 },
    skills: parseList('Mimicry'),
    nectars: parseList('Perfect Balance'),
    thorns: parseList('Identity Echo'),
    seedKV: 245, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Void-Singer',
    description: 'Cosmic bards who sing the songs of creation and destruction but risk madness from cosmic truths.',
    baseFateDie: fateDie(4),
    frequency: 20,
    fatedAge: 400,
    baseResist: 16,
    attributes: { clout: 5, celerity: 8, constitution: 8, focus: 14, flow: 16, willpower: 10, wisdom: 12, wit: 7 },
    skills: parseList('Void Songs'),
    nectars: parseList('Reality Harmonics'),
    thorns: parseList('Sanity Strain'),
    seedKV: 495, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Flame-Heart',
    description: 'Beings with hearts of elemental fire granting immunity and power but constant heat requirements.',
    baseFateDie: fateDie(6),
    frequency: 40,
    fatedAge: 200,
    baseResist: 18,
    attributes: { clout: 12, celerity: 8, constitution: 12, focus: 8, flow: 10, willpower: 12, wisdom: 6, wit: 6 },
    skills: parseList('Fire Immunity'),
    nectars: parseList('Eternal Flame'),
    thorns: parseList('Heat Dependency'),
    seedKV: 550, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Phase-Spider',
    description: 'Arachnid beings capable of moving between dimensional phases but suffering spatial disconnection.',
    baseFateDie: fateDie(8),
    frequency: 35,
    fatedAge: 30,
    baseResist: 15,
    attributes: { clout: 6, celerity: 14, constitution: 8, focus: 10, flow: 8, willpower: 6, wisdom: 8, wit: 12 },
    skills: parseList('Web-Spinning'),
    nectars: parseList('Multi-Dimensional'),
    thorns: parseList('Spatial Instability'),
    seedKV: 550, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Memory-Keeper',
    description: 'Beings who retain perfect memories of their lineage but suffer from information cascade overload.',
    baseFateDie: fateDie(6),
    frequency: 25,
    fatedAge: 300,
    baseResist: 14,
    attributes: { clout: 4, celerity: 6, constitution: 6, focus: 12, flow: 10, willpower: 16, wisdom: 16, wit: 8 },
    skills: parseList('Perfect Recall'),
    nectars: parseList('Ancestral Memories'),
    thorns: parseList('Information Overload'),
    seedKV: 410, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Storm-Child',
    description: 'Humanoids born during cosmic storms with electrical affinity but uncontrolled energy discharge.',
    baseFateDie: fateDie(4),
    frequency: 35,
    fatedAge: 70,
    baseResist: 12,
    attributes: { clout: 8, celerity: 12, constitution: 6, focus: 12, flow: 14, willpower: 8, wisdom: 10, wit: 6 },
    skills: parseList('Weather Sense'),
    nectars: parseList('Lightning Affinity'),
    thorns: parseList('Static Discharge'),
    seedKV: 175, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Rust-Born',
    description: 'Beings born in technological ruins with immunity to decay but corrosive effects on surroundings.',
    baseFateDie: fateDie(6),
    frequency: 45,
    fatedAge: 120,
    baseResist: 19,
    attributes: { clout: 10, celerity: 6, constitution: 16, focus: 6, flow: 4, willpower: 8, wisdom: 4, wit: 12 },
    skills: parseList('Scrap Engineering'),
    nectars: parseList('Decay Immunity'),
    thorns: parseList('Corrosive Touch'),
    seedKV: 700, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Moon-Blessed',
    description: 'Nocturnal beings blessed by lunar forces with enhanced night abilities but daylight vulnerability.',
    baseFateDie: fateDie(4),
    frequency: 25,
    fatedAge: 180,
    baseResist: 13,
    attributes: { clout: 6, celerity: 10, constitution: 6, focus: 14, flow: 16, willpower: 12, wisdom: 14, wit: 6 },
    skills: parseList('Lunar Cycles'),
    nectars: parseList('Night Vision'),
    thorns: parseList('Lunar Dependency'),
    seedKV: 165, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Blood-Bound',
    description: 'Warriors bound by blood pacts granting regenerative abilities but compulsive bloodlust.',
    baseFateDie: fateDie(6),
    frequency: 40,
    fatedAge: 250,
    baseResist: 17,
    attributes: { clout: 10, celerity: 8, constitution: 14, focus: 6, flow: 8, willpower: 12, wisdom: 8, wit: 8 },
    skills: parseList('Blood Magic'),
    nectars: parseList('Regeneration'),
    thorns: parseList('Thirst Compulsion'),
    seedKV: 550, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Thought-Form',
    description: 'Beings of pure thought given physical form with incredible mental abilities but fragile bodies.',
    baseFateDie: fateDie(8),
    frequency: 20,
    fatedAge: 50,
    baseResist: 11,
    attributes: { clout: 2, celerity: 6, constitution: 2, focus: 18, flow: 12, willpower: 8, wisdom: 16, wit: 16 },
    skills: parseList('Mental Projection'),
    nectars: parseList('Telepathic Network'),
    thorns: parseList('Physical Weakness'),
    seedKV: 585, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Gravity-Walker',
    description: 'Beings adapted to variable gravity with enhanced spatial awareness but unstable physical density.',
    baseFateDie: fateDie(6),
    frequency: 30,
    fatedAge: 110,
    baseResist: 16,
    attributes: { clout: 8, celerity: 10, constitution: 10, focus: 12, flow: 6, willpower: 10, wisdom: 8, wit: 10 },
    skills: parseList('Zero-G Movement'),
    nectars: parseList('Gravitational Sense'),
    thorns: parseList('Density Fluctuation'),
    seedKV: 510, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Nano-Swarm',
    description: 'Collections of nanoscopic entities forming humanoid appearance with technological mastery but unstable cohesion.',
    baseFateDie: fateDie(8),
    frequency: 25,
    fatedAge: 200,
    baseResist: 12,
    attributes: { clout: 6, celerity: 8, constitution: 6, focus: 14, flow: 10, willpower: 6, wisdom: 10, wit: 16 },
    skills: parseList('Microscopic Control'),
    nectars: parseList('Collective Consciousness'),
    thorns: parseList('Cohesion Instability'),
    seedKV: 3460, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Echo-Phantom',
    description: 'Ghostly beings partially anchored to reality with phase abilities but vulnerable to physical disruption.',
    baseFateDie: fateDie(4),
    frequency: 20,
    fatedAge: 100,
    baseResist: 12,
    attributes: { clout: 5, celerity: 12, constitution: 5, focus: 10, flow: 12, willpower: 10, wisdom: 12, wit: 8 },
    skills: parseList('Phase Walk'),
    nectars: parseList('Spectral Form'),
    thorns: parseList('Corporeal Weakness'),
    seedKV: 170, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Prism-Born',
    description: 'Crystalline beings who manipulate light and color but suffer from sensory overload in complex environments.',
    baseFateDie: fateDie(6),
    frequency: 30,
    fatedAge: 400,
    baseResist: 17,
    attributes: { clout: 6, celerity: 8, constitution: 8, focus: 12, flow: 12, willpower: 8, wisdom: 10, wit: 10 },
    skills: parseList('Light Manipulation'),
    nectars: parseList('Spectrum Vision'),
    thorns: parseList('Chromatic Overload'),
    seedKV: 405, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Star-Scar',
    description: 'Beings scarred by stellar radiation with cosmic attunement but perpetual radiation damage.',
    baseFateDie: fateDie(8),
    frequency: 15,
    fatedAge: 600,
    baseResist: 18,
    attributes: { clout: 8, celerity: 6, constitution: 12, focus: 12, flow: 8, willpower: 12, wisdom: 12, wit: 8 },
    skills: parseList('Cosmic Resilience'),
    nectars: parseList('Stellar Navigation'),
    thorns: parseList('Radiation Burn'),
    seedKV: 1165, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Hive-Mind',
    description: 'Members of collective consciousness with shared knowledge but suppressed individual identity.',
    baseFateDie: fateDie(6),
    frequency: 35,
    fatedAge: 40,
    baseResist: 15,
    attributes: { clout: 8, celerity: 8, constitution: 8, focus: 10, flow: 8, willpower: 8, wisdom: 8, wit: 12 },
    skills: parseList('Collective Thinking'),
    nectars: parseList('Shared Consciousness'),
    thorns: parseList('Individual Suppression'),
    seedKV: 405, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Warp-Touched',
    description: 'Beings touched by chaotic warp energies with reality manipulation but unpredictable mutations.',
    baseFateDie: fateDie(4),
    frequency: 25,
    fatedAge: 90,
    baseResist: 14,
    attributes: { clout: 7, celerity: 9, constitution: 7, focus: 11, flow: 11, willpower: 9, wisdom: 9, wit: 11 },
    skills: parseList('Reality Sense'),
    nectars: parseList('Dimensional Shift'),
    thorns: parseList('Chaos Mutation'),
    seedKV: 370, bodyStructure: HUMANOID_BODY,
  },
  {
    name: 'Soul-Echo',
    description: 'Beings who carry echoes of previous souls with ancestral wisdom but inherited psychological damage.',
    baseFateDie: fateDie(6),
    frequency: 20,
    fatedAge: 250,
    baseResist: 16,
    attributes: { clout: 6, celerity: 6, constitution: 10, focus: 8, flow: 14, willpower: 12, wisdom: 14, wit: 8 },
    skills: parseList('Spirit Communication'),
    nectars: parseList('Ancestral Guidance'),
    thorns: parseList('Past Trauma'),
    seedKV: 555, bodyStructure: HUMANOID_BODY,
  },
];

// Lookup helpers
export const SEED_BY_NAME: Record<string, GrowthSeed> = Object.fromEntries(
  SEED_CATALOG.map(s => [s.name, s])
);

export function getSeed(name: string): GrowthSeed | undefined {
  return SEED_BY_NAME[name];
}

// KV range for UI display
export const SEED_KV_RANGE = {
  min: Math.min(...SEED_CATALOG.map(s => s.seedKV)),
  max: Math.max(...SEED_CATALOG.map(s => s.seedKV)),
};

// Fate die to numeric value (for sorting/filtering)
export const FATE_DIE_VALUE: Record<FateDie, number> = {
  'd4': 4, 'd6': 6, 'd8': 8, 'd12': 12, 'd20': 20,
};
