/**
 * Modern-Earth items — electronics, medical, weapons.
 *
 * Weapons anchor to canon examples (Weapon_System.md, natural-alignment
 * targeting only): .38 Revolver 18P→Clout / .45 Revolver 22P→Clout are
 * documented; the rest grade against them. Damage KV counts 1:1 at natural
 * ring targeting. Medical items are the counterplay half of several thorns
 * (Inhaler↔Asthma, EpiPen↔Severe Allergy, Insulin↔Type 1 Diabetes,
 * Wheelchair↔Paraplegia, Glasses↔Severely Nearsighted, Hearing Aids↔Hard of
 * Hearing, Prosthetic Hand↔Missing Hand).
 */

import type { ItemTemplate } from './types';

export const TECH_ITEMS: ItemTemplate[] = [
  {
    name: 'Smartphone', itemType: 'accessory',
    description: 'Phone, camera, map, library, wallet, flashlight, and distraction engine in one glass slab.',
    primaryMaterial: 'Glass', subordinateMaterials: ['Aluminum'], materialClass: 'Hard',
    weightLbs: 0.4, rarity: 1, properties: ['Fragile', 'Electric Vulnerable'],
    itemAbilities: [
      { name: 'Connected', description: 'Where signal exists: instant communication, navigation (no checks), and Research checks anywhere at +1.', kv: 8 },
      { name: 'Camera & Records', description: 'Capture and store evidence; documented facts can\'t be plausibly denied.', kv: 3 },
      { name: 'Dead Battery', description: 'Requires daily charging; GM may declare it dead at a dramatic moment once per session if uncharged.', kv: -2 },
    ],
    kv: 10, tags: ['electronics', 'modern'],
  },
  {
    name: 'Burner Phone', itemType: 'accessory',
    description: 'Prepaid, plastic, forgettable. Exists to be thrown away.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.3, rarity: 1,
    itemAbilities: [{ name: 'Untraceable Line', description: 'Calls and texts that don\'t tie back to the owner. Attempts to trace it take −3.', kv: 4 }],
    kv: 5, tags: ['electronics', 'modern'],
  },
  {
    name: 'Laptop', itemType: 'tool',
    description: 'A folding workspace: documents, code, comms, and every rabbit hole ever dug.',
    primaryMaterial: 'Aluminum', subordinateMaterials: ['Glass'], materialClass: 'Hard',
    weightLbs: 3, rarity: 2, properties: ['Fragile', 'Electric Vulnerable'],
    itemAbilities: [{ name: 'Workstation', description: 'Enables Programming, deep Research, and document work in the field; such checks gain +1.', kv: 8 }],
    kv: 10, tags: ['electronics', 'modern'],
  },
  {
    name: 'Tablet', itemType: 'accessory',
    description: 'A window that shows anything except where you left it.',
    primaryMaterial: 'Glass', subordinateMaterials: ['Aluminum'], materialClass: 'Hard',
    weightLbs: 1, rarity: 1, properties: ['Fragile'],
    itemAbilities: [{ name: 'Reference Screen', description: 'Maps, manuals, and media at hand; +1 to checks that benefit from live reference.', kv: 4 }],
    kv: 5, tags: ['electronics', 'modern'],
  },
  {
    name: 'DSLR Camera', itemType: 'tool',
    description: 'Glass and sensor tuned to catch the exact truth of a moment.',
    primaryMaterial: 'Polymer', subordinateMaterials: ['Glass'], materialClass: 'Hard',
    weightLbs: 2, rarity: 2, properties: ['Fragile'],
    itemAbilities: [{ name: 'Professional Optics', description: 'Photography checks gain +2; usable evidence at distances phones can\'t reach.', kv: 5 }],
    kv: 6, tags: ['electronics', 'modern'],
  },
  {
    name: 'Consumer Drone', itemType: 'tool',
    description: 'A flying camera with twenty minutes of courage.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 2, rarity: 3, properties: ['Fragile', 'Electric Vulnerable'],
    itemAbilities: [{ name: 'Eye in the Sky', description: 'Aerial reconnaissance within a mile (Piloting to fly); 20 minutes per charge.', kv: 8 }],
    kv: 9, tags: ['electronics', 'modern'],
  },
  {
    name: 'Walkie-Talkie Pair', itemType: 'tool',
    description: 'Two radios, one channel, zero dependence on anyone\'s network.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 1, rarity: 1,
    itemAbilities: [{ name: 'Off-Grid Comms', description: 'Team communication within ~2 miles, no signal infrastructure needed.', kv: 4 }],
    kv: 5, tags: ['electronics', 'modern'],
  },
  {
    name: 'Power Bank', itemType: 'accessory',
    description: 'A brick of stored tomorrow.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.8, rarity: 1,
    itemAbilities: [{ name: 'Reserve Charge', description: 'Negates one Dead Battery declaration; recharges overnight.', kv: 2 }],
    kv: 3, tags: ['electronics', 'modern'],
  },
  {
    name: 'GPS Unit (Handheld)', itemType: 'tool',
    description: 'Knows where you are even when you emphatically do not.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.5, rarity: 2, properties: ['Strong'],
    itemAbilities: [{ name: 'Waypoint', description: 'Navigation checks auto-succeed under open sky; works where phones die.', kv: 4 }],
    kv: 5, tags: ['electronics', 'outdoor', 'modern'],
  },
  {
    name: 'Laptop-Grade External Drive', itemType: 'accessory',
    description: 'Two terabytes of secrets, pocket-sized.',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 0.2, rarity: 1,
    kv: 2, tags: ['electronics', 'modern'],
  },
];

export const MEDICAL_ITEMS: ItemTemplate[] = [
  {
    name: 'Prescription Glasses', itemType: 'accessory',
    description: 'The world, refocused. (Counterplay: Severely Nearsighted.)',
    primaryMaterial: 'Polycarbonate', subordinateMaterials: ['Titanium'], materialClass: 'Hard',
    weightLbs: 0.1, rarity: 1, properties: ['Fragile'],
    itemAbilities: [{ name: 'Correction', description: 'Negates the Severely Nearsighted penalty while worn intact.', kv: 3 }],
    kv: 4, tags: ['medical', 'modern'],
  },
  {
    name: 'Inhaler', itemType: 'consumable',
    description: 'A pocket lung ally. (Counterplay: Asthma.)',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.1, rarity: 2,
    itemAbilities: [{ name: 'Rescue Dose', description: 'Instantly clears an Asthma flare. ~20 doses; losing it matters.', kv: 4 }],
    kv: 5, tags: ['medical', 'modern'],
  },
  {
    name: 'EpiPen', itemType: 'consumable',
    description: 'One loaded answer to anaphylaxis. (Counterplay: Severe Allergy.)',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.1, rarity: 2,
    itemAbilities: [{ name: 'Epinephrine', description: 'Immediately ends a Severe Allergy reaction. Single use.', kv: 4 }],
    kv: 5, tags: ['medical', 'modern'],
  },
  {
    name: 'Insulin Kit', itemType: 'consumable',
    description: 'A month of manual pancreas, refrigeration preferred. (Counterplay: Type 1 Diabetes.)',
    primaryMaterial: 'Glass', subordinateMaterials: ['Polymer'], materialClass: 'Hard',
    weightLbs: 1, rarity: 3, properties: ['Fragile'],
    itemAbilities: [{ name: 'Daily Doses', description: '30 daily doses for Type 1 Diabetes. Spoils if kept hot for days (GM call).', kv: 4 }],
    kv: 5, tags: ['medical', 'modern'],
  },
  {
    name: 'Wheelchair (Everyday)', itemType: 'tool',
    description: 'Lightweight frame, quick wheels, zero apologies. (Pairs: Paraplegia.)',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 30, rarity: 2, baseResist: 5, properties: ['Strong'],
    itemAbilities: [{ name: 'Mobility', description: 'Normal movement on accessible ground; trained users take no penalty in a chase on pavement.', kv: 6 }],
    kv: 8, tags: ['medical', 'mobility', 'modern'],
  },
  {
    name: 'Hearing Aids', itemType: 'accessory',
    description: 'The soundtrack, restored in high fidelity. (Counterplay: Hard of Hearing.)',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.05, rarity: 2, properties: ['Fragile', 'Electric Vulnerable'],
    itemAbilities: [{ name: 'Amplification', description: 'Negates Hard of Hearing penalties while worn and charged.', kv: 4 }],
    kv: 5, tags: ['medical', 'modern'],
  },
  {
    name: 'Prosthetic Hand (Body-Powered)', itemType: 'tool',
    description: 'Cable, harness, and hook or hand: dependable, unpowered, honest. (Pairs: Missing Hand.)',
    primaryMaterial: 'Polymer', subordinateMaterials: ['Steel'], materialClass: 'Hard',
    weightLbs: 1.5, rarity: 3, baseResist: 4,
    itemAbilities: [{ name: 'Grip Restored', description: 'Two-handed actions become possible; fine-motor tasks with this hand take −1.', kv: 6 }],
    kv: 8, tags: ['medical', 'modern'],
  },
  {
    name: 'Trauma Kit', itemType: 'consumable',
    description: 'Tourniquet, chest seal, hemostatic gauze: the difference between minutes and enough minutes.',
    primaryMaterial: 'Fabric', subordinateMaterials: ['Polymer'], materialClass: 'Soft',
    weightLbs: 3, rarity: 3,
    itemAbilities: [{ name: 'Stabilize', description: 'First Aid on serious wounds gains +3; once per kit, keep a character at Death\'s Door stable without a check. 3 uses.', kv: 6 }],
    kv: 7, tags: ['medical', 'modern'],
  },
];

export const WEAPON_ITEMS: ItemTemplate[] = [
  {
    name: 'Pocket Knife', itemType: 'weapon',
    description: 'Three inches of folding practicality.',
    primaryMaterial: 'Stainless Steel', materialClass: 'Hard',
    weightLbs: 0.2, rarity: 1, properties: ['Sharp'],
    damage: { slashing: 4 }, range: 'melee', targetAttribute: 'celerity',
    kv: 5, tags: ['weapon', 'tool', 'modern'],
  },
  {
    name: 'Hunting Knife', itemType: 'weapon',
    description: 'Fixed blade, full tang, born for the field.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Leather'], materialClass: 'Hard',
    weightLbs: 0.8, rarity: 1, properties: ['Sharp', 'Strong'],
    damage: { slashing: 8, piercing: 4 }, range: 'melee', targetAttribute: 'celerity',
    kv: 13, tags: ['weapon', 'outdoor', 'modern'],
  },
  {
    name: 'Machete', itemType: 'weapon',
    description: 'Agriculture\'s most persuasive export.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 1.5, rarity: 2, properties: ['Sharp'],
    damage: { slashing: 12 }, range: 'melee', targetAttribute: 'celerity',
    kv: 13, tags: ['weapon', 'outdoor', 'modern'],
  },
  {
    name: 'Baseball Bat (Aluminum)', itemType: 'weapon',
    description: 'A sporting good until it very much is not.',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 2, rarity: 1, properties: ['Strong'],
    damage: { bashing: 10 }, range: 'melee', targetAttribute: 'wisdom',
    kv: 11, tags: ['weapon', 'sport', 'modern'],
  },
  {
    name: 'Pepper Spray', itemType: 'consumable',
    description: 'Ten feet of no.',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 0.2, rarity: 1,
    damage: { decay: 4 }, range: 'short', targetAttribute: 'focus',
    itemAbilities: [{ name: 'Blind & Burn', description: 'Target passes DR5 Constitution or takes −3 to all checks for the scene. ~5 uses.', kv: 3 }],
    kv: 8, tags: ['weapon', 'defense', 'modern'],
  },
  {
    name: 'Taser (Civilian)', itemType: 'weapon',
    description: 'Fifty thousand volts of pause button.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 0.5, rarity: 3,
    damage: { energy: 8 }, range: 'short', targetAttribute: 'wit', shots: 1, reload: 'replace cartridge (1 action)',
    itemAbilities: [{ name: 'Incapacitate', description: 'On a hit, target passes DR7 Constitution or loses their next action.', kv: 5 }],
    kv: 14, tags: ['weapon', 'defense', 'modern'],
  },
  {
    name: 'Compound Bow', itemType: 'weapon',
    description: 'Cams and cables turn patience into penetration.',
    primaryMaterial: 'Aluminum', subordinateMaterials: ['Carbon Fiber'], materialClass: 'Hard',
    weightLbs: 4, rarity: 2, properties: ['Strong'],
    damage: { piercing: 14 }, range: 'medium', targetAttribute: 'clout',
    kv: 16, tags: ['weapon', 'sport', 'modern'],
  },
  {
    name: '.38 Revolver', itemType: 'weapon',
    description: 'Six chambers of old-school reliability. (Canon-anchored.)',
    primaryMaterial: 'Steel', subordinateMaterials: ['Walnut'], materialClass: 'Hard',
    weightLbs: 1.5, rarity: 4, properties: ['Strong'],
    damage: { piercing: 18 }, range: 'short', targetAttribute: 'clout', shots: 6, reload: 'speedloader (1 action)',
    kv: 20, tags: ['weapon', 'firearm', 'restricted', 'modern'],
  },
  {
    name: '.45 Revolver', itemType: 'weapon',
    description: 'The heavyweight opinion. (Canon-anchored.)',
    primaryMaterial: 'Steel', subordinateMaterials: ['Walnut'], materialClass: 'Hard',
    weightLbs: 2.2, rarity: 4, properties: ['Strong'],
    damage: { piercing: 22 }, range: 'short', targetAttribute: 'clout', shots: 6, reload: 'speedloader (1 action)',
    kv: 24, tags: ['weapon', 'firearm', 'restricted', 'modern'],
  },
  {
    name: '9mm Pistol', itemType: 'weapon',
    description: 'The modern sidearm default: polymer frame, fifteen rounds, no romance.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Polymer'], materialClass: 'Hard',
    weightLbs: 1.6, rarity: 4, properties: ['Strong'],
    damage: { piercing: 19 }, range: 'short', targetAttribute: 'clout', shots: 15, reload: 'magazine (1 action)',
    itemAbilities: [{ name: 'High Capacity', description: 'Rarely counts rounds in a single scene.', kv: 2 }],
    kv: 23, tags: ['weapon', 'firearm', 'restricted', 'modern'],
  },
  {
    name: 'Pump Shotgun (12ga)', itemType: 'weapon',
    description: 'The sound alone is a negotiation tactic.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Walnut'], materialClass: 'Hard',
    weightLbs: 7.5, rarity: 4, properties: ['Strong'],
    damage: { piercing: 24 }, range: 'short', targetAttribute: 'clout', shots: 5, reload: 'shell by shell',
    itemAbilities: [{ name: 'Spread', description: 'At short range, +2 to hit; at medium+, −4 damage.', kv: 3 }],
    kv: 28, tags: ['weapon', 'firearm', 'restricted', 'modern'],
  },
  {
    name: 'Hunting Rifle (Bolt-Action)', itemType: 'weapon',
    description: 'One round, well placed, from very far away.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Walnut'], materialClass: 'Hard',
    weightLbs: 8, rarity: 4, properties: ['Strong'],
    damage: { piercing: 28 }, range: 'long', targetAttribute: 'clout', shots: 5, reload: 'bolt cycle (free), magazine (1 action)',
    itemAbilities: [{ name: 'Scoped', description: 'Aimed shots at long range take no range penalty after one round of aiming.', kv: 4 }],
    kv: 33, tags: ['weapon', 'firearm', 'restricted', 'modern'],
  },
];
