/**
 * Modern-Earth items — household, kitchen, tools, office, outdoor, clothing.
 *
 * Grading method (r-2026-04-22-15: case-by-case, material floor):
 *   KV = material floor (0.5-2, rounded into total) + damage (1:1 at natural
 *   ring targeting) + 2×baseResist (protective role only) + graded abilities.
 * Mundane items land KV 1-3 by design — a household is cheap; its STORY is
 * carried by facts and traits, not gear price. Real weights in lbs.
 */

import type { ItemTemplate } from './types';

export const EVERYDAY_ITEMS: ItemTemplate[] = [
  // ── Kitchen & household ──
  {
    name: 'Chef\'s Knife', itemType: 'tool',
    description: 'Eight inches of honest steel; the kitchen\'s workhorse and, in a pinch, an argument.',
    primaryMaterial: 'Stainless Steel', subordinateMaterials: ['Polymer'], materialClass: 'Hard',
    weightLbs: 0.6, rarity: 1, properties: ['Sharp'],
    damage: { slashing: 5 }, range: 'melee', targetAttribute: 'celerity',
    kv: 6, tags: ['kitchen', 'modern'],
  },
  {
    name: 'Cast-Iron Skillet', itemType: 'tool',
    description: 'Seasoned by a decade of breakfasts. Cooks evenly, swings convincingly.',
    primaryMaterial: 'Cast Iron', materialClass: 'Hard',
    weightLbs: 6, rarity: 1, baseResist: 6, properties: ['Strong', 'Heat Resistant'],
    damage: { bashing: 6 }, range: 'melee', targetAttribute: 'wisdom',
    kv: 8, tags: ['kitchen', 'modern'],
  },
  {
    name: 'Kitchen Kit', itemType: 'tool',
    description: 'Pots, pans, boards, and utensils — everything a working kitchen needs short of talent.',
    primaryMaterial: 'Stainless Steel', subordinateMaterials: ['Wood'], materialClass: 'Hard',
    weightLbs: 25, rarity: 1,
    itemAbilities: [{ name: 'Full Kitchen', description: 'Cooking checks made with a proper kitchen setup gain +1.', kv: 2 }],
    kv: 3, tags: ['kitchen', 'modern'],
  },
  {
    name: 'Refrigerator', itemType: 'misc',
    description: 'The cold heart of the household. Hums, keeps things alive longer than they deserve.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Polymer'], materialClass: 'Hard',
    weightLbs: 250, rarity: 1, baseResist: 6,
    itemAbilities: [{ name: 'Preservation', description: 'Perishables stored inside keep for their full natural span.', kv: 1 }],
    kv: 3, tags: ['household', 'appliance', 'modern'],
  },
  {
    name: 'Microwave Oven', itemType: 'misc',
    description: 'Ninety seconds from cold to edible. Civilization\'s quiet triumph.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Glass'], materialClass: 'Hard',
    weightLbs: 25, rarity: 1, kv: 2, tags: ['household', 'appliance', 'modern'],
  },
  {
    name: 'Coffee Maker', itemType: 'misc',
    description: 'The household\'s true alarm clock.',
    primaryMaterial: 'Polymer', subordinateMaterials: ['Glass'], materialClass: 'Hard',
    weightLbs: 7, rarity: 1,
    itemAbilities: [{ name: 'Morning Ritual', description: 'Grants the Caffeinated blossom to one character per brew cycle.', kv: 1 }],
    kv: 2, tags: ['household', 'appliance', 'modern'],
  },
  {
    name: 'Flashlight (LED)', itemType: 'tool',
    description: 'Three hundred lumens of portable noon.',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 0.5, rarity: 1,
    itemAbilities: [{ name: 'Beam', description: 'Negates darkness penalties in its cone; can dazzle at close range (DR5 resist or −1 next check).', kv: 2 }],
    kv: 3, tags: ['household', 'tool', 'modern'],
  },
  {
    name: 'First Aid Kit', itemType: 'consumable',
    description: 'Bandages, antiseptic, tape, and the confidence to use them. Ten uses of not-panicking.',
    primaryMaterial: 'Fabric', subordinateMaterials: ['Polymer'], materialClass: 'Soft',
    weightLbs: 2, rarity: 1,
    itemAbilities: [{ name: 'Field Care', description: 'First Aid checks using the kit gain +2. Ten uses.', kv: 3 }],
    kv: 4, tags: ['medical', 'modern'],
  },
  {
    name: 'Fire Extinguisher', itemType: 'tool',
    description: 'Red, heavy, and utterly indifferent to what the fire wanted.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 10, rarity: 1,
    itemAbilities: [{ name: 'Suppress', description: 'Extinguishes a room-scale fire in one action (one full discharge).', kv: 3 }],
    kv: 4, tags: ['household', 'safety', 'modern'],
  },
  {
    name: 'Lighter', itemType: 'tool',
    description: 'Fire on demand, pocket-sized.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 0.1, rarity: 1, properties: ['Flammable'],
    kv: 1, tags: ['household', 'modern'],
  },
  {
    name: 'Sleeping Bag', itemType: 'misc',
    description: 'A portable bed rated for weather it will hopefully never meet.',
    primaryMaterial: 'Nylon', subordinateMaterials: ['Down'], materialClass: 'Soft',
    weightLbs: 3, rarity: 1,
    itemAbilities: [{ name: 'Shelter Sleep', description: 'Permits a full night\'s rest outdoors in non-extreme weather.', kv: 2 }],
    kv: 3, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Duct Tape', itemType: 'consumable',
    description: 'Silver salvation, sixty yards. If it moves and shouldn\'t: this.',
    primaryMaterial: 'Polymer', subordinateMaterials: ['Fabric'], materialClass: 'Soft',
    weightLbs: 0.8, rarity: 1,
    itemAbilities: [{ name: 'Field Fix', description: 'Once per scene, temporarily restore a Broken (condition 1) item to Worn (2) until scene\'s end.', kv: 3 }],
    kv: 4, tags: ['tool', 'modern'],
  },

  // ── Tools ──
  {
    name: 'Claw Hammer', itemType: 'tool',
    description: 'Drives nails, pulls nails, settles disputes with drywall.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Fiberglass'], materialClass: 'Hard',
    weightLbs: 1.5, rarity: 1, properties: ['Strong'],
    damage: { bashing: 7 }, range: 'melee', targetAttribute: 'wisdom',
    kv: 9, tags: ['tool', 'modern'],
  },
  {
    name: 'Toolbox (Stocked)', itemType: 'tool',
    description: 'Screwdrivers, wrenches, sockets, pliers, and the one bit that always goes missing.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 20, rarity: 1, baseResist: 5,
    itemAbilities: [{ name: 'Right Tool', description: 'Mechanics and repair checks with the box at hand gain +2.', kv: 4 }],
    kv: 6, tags: ['tool', 'modern'],
  },
  {
    name: 'Power Drill', itemType: 'tool',
    description: 'Cordless torque with a battery that dies exactly one screw early.',
    primaryMaterial: 'Polymer', subordinateMaterials: ['Steel'], materialClass: 'Hard',
    weightLbs: 3.5, rarity: 1,
    itemAbilities: [{ name: 'Fast Assembly', description: 'Construction and disassembly tasks take half the time.', kv: 2 }],
    kv: 3, tags: ['tool', 'modern'],
  },
  {
    name: 'Circular Saw', itemType: 'tool',
    description: 'A spinning argument that wood always loses.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Polymer'], materialClass: 'Hard',
    weightLbs: 9, rarity: 2, properties: ['Sharp'],
    damage: { slashing: 10 }, range: 'melee', targetAttribute: 'celerity',
    itemAbilities: [{ name: 'Unwieldy', description: 'As a weapon: −2 to hit, requires both hands and a power source or charge.', kv: -3 }],
    kv: 9, tags: ['tool', 'modern'],
  },
  {
    name: 'Crowbar', itemType: 'tool',
    description: 'Leverage, embodied. Doors, crates, and assumptions all open eventually.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 5, rarity: 1, baseResist: 8, properties: ['Strong'],
    damage: { bashing: 8 }, range: 'melee', targetAttribute: 'wisdom',
    itemAbilities: [{ name: 'Pry', description: 'Forcing checks (doors, lids, crates) gain +2.', kv: 3 }],
    kv: 12, tags: ['tool', 'modern'],
  },
  {
    name: 'Bolt Cutters', itemType: 'tool',
    description: 'The universal password for padlocks and chain-link.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 8, rarity: 2, properties: ['Strong', 'Sharp'],
    itemAbilities: [{ name: 'Shear', description: 'Cuts chain, padlock shackles, and wire fencing without a check (hardened locks: DR5 Clout).', kv: 4 }],
    kv: 5, tags: ['tool', 'modern'],
  },
  {
    name: 'Chainsaw', itemType: 'tool',
    description: 'Forestry equipment with a reputation problem.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Polymer'], materialClass: 'Hard',
    weightLbs: 12, rarity: 3, properties: ['Sharp'],
    damage: { slashing: 14 }, range: 'melee', targetAttribute: 'celerity',
    itemAbilities: [
      { name: 'Timber', description: 'Fells trees and cuts structural lumber without a check.', kv: 3 },
      { name: 'Unwieldy', description: 'As a weapon: −2 to hit, loud, needs fuel, both hands.', kv: -4 },
    ],
    kv: 14, tags: ['tool', 'modern'],
  },
  {
    name: 'Extension Ladder (16ft)', itemType: 'tool',
    description: 'Sixteen feet of vertical permission.',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 30, rarity: 1,
    itemAbilities: [{ name: 'Access', description: 'Reach second-story height without a climbing check.', kv: 2 }],
    kv: 3, tags: ['tool', 'modern'],
  },
  {
    name: 'Shovel', itemType: 'tool',
    description: 'For gardens, graves, and everything the two have in common.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Wood'], materialClass: 'Hard',
    weightLbs: 5, rarity: 1,
    damage: { bashing: 6 }, range: 'melee', targetAttribute: 'wisdom',
    kv: 7, tags: ['tool', 'modern'],
  },
  {
    name: 'Axe (Felling)', itemType: 'tool',
    description: 'Older than every other tool in the shed and still undefeated.',
    primaryMaterial: 'Steel', subordinateMaterials: ['Hickory'], materialClass: 'Hard',
    weightLbs: 4, rarity: 1, properties: ['Sharp', 'Strong'],
    damage: { slashing: 12 }, range: 'melee', targetAttribute: 'celerity',
    kv: 13, tags: ['tool', 'weapon', 'modern'],
  },

  // ── Clothing & worn protection ──
  {
    name: 'Everyday Outfit', itemType: 'armor',
    description: 'Jeans, shirt, jacket, sneakers: the urban default loadout.',
    primaryMaterial: 'Cotton', subordinateMaterials: ['Denim'], materialClass: 'Soft',
    weightLbs: 4, rarity: 1, baseResist: 1, armorCategory: 'Clothing',
    kv: 1, tags: ['clothing', 'modern'],
  },
  {
    name: 'Business Suit', itemType: 'armor',
    description: 'Armor for rooms where the weapons are agendas.',
    primaryMaterial: 'Wool', materialClass: 'Soft',
    weightLbs: 4, rarity: 2, baseResist: 1, armorCategory: 'Clothing',
    itemAbilities: [{ name: 'Dressed the Part', description: 'First-impression checks in formal or corporate settings gain +1.', kv: 3 }],
    kv: 4, tags: ['clothing', 'modern'],
  },
  {
    name: 'Winter Coat', itemType: 'armor',
    description: 'A wearable furnace with pockets.',
    primaryMaterial: 'Nylon', subordinateMaterials: ['Down'], materialClass: 'Soft',
    weightLbs: 3.5, rarity: 1, baseResist: 2, armorCategory: 'Clothing', properties: ['Cold Resistant'],
    kv: 3, tags: ['clothing', 'modern'],
  },
  {
    name: 'Work Boots (Steel Toe)', itemType: 'armor',
    description: 'OSHA-approved and kick-rated.',
    primaryMaterial: 'Leather', subordinateMaterials: ['Steel'], materialClass: 'Soft',
    weightLbs: 4, rarity: 1, baseResist: 3, armorCategory: 'Clothing', properties: ['Protective'],
    kv: 3, tags: ['clothing', 'modern'],
  },
  {
    name: 'Motorcycle Jacket & Gear', itemType: 'armor',
    description: 'Armored leather and pads engineered for the argument between rider and road.',
    primaryMaterial: 'Leather', subordinateMaterials: ['Polymer'], materialClass: 'Soft',
    weightLbs: 8, rarity: 2, baseResist: 5, armorCategory: 'Light', properties: ['Protective', 'Flexible'],
    kv: 12, tags: ['clothing', 'armor', 'modern'],
  },
  {
    name: 'Kevlar Vest', itemType: 'armor',
    description: 'Soft body armor, concealable under a loose shirt. Rated for the worst minute of someone\'s life.',
    primaryMaterial: 'Kevlar', materialClass: 'Soft',
    weightLbs: 5.5, rarity: 5, baseResist: 8, armorCategory: 'Light', properties: ['Protective', 'Flexible'],
    kv: 20, tags: ['armor', 'restricted', 'modern'],
  },
  {
    name: 'Riot Armor Set', itemType: 'armor',
    description: 'Hard shells over padding, helmet to shins. Built for bottles, batons, and bad nights.',
    primaryMaterial: 'Polycarbonate', subordinateMaterials: ['Foam Padding'], materialClass: 'Hard',
    weightLbs: 18, rarity: 6, baseResist: 10, armorCategory: 'Heavy', properties: ['Protective', 'Restrictive'],
    kv: 24, tags: ['armor', 'restricted', 'modern'],
  },
  {
    name: 'Motorcycle Helmet', itemType: 'armor',
    description: 'The last disagreement your skull ever needs to win.',
    primaryMaterial: 'Polycarbonate', subordinateMaterials: ['Foam Padding'], materialClass: 'Hard',
    weightLbs: 3.5, rarity: 1, baseResist: 6, armorCategory: 'Light', properties: ['Protective'],
    kv: 13, tags: ['clothing', 'armor', 'modern'],
  },

  // ── Outdoor ──
  {
    name: 'Hiking Backpack (65L)', itemType: 'accessory',
    description: 'A house you wear: frame, straps, and room for a week.',
    primaryMaterial: 'Nylon', subordinateMaterials: ['Aluminum'], materialClass: 'Soft',
    weightLbs: 5, rarity: 1,
    itemAbilities: [{ name: 'Load Bearing', description: 'Carried gear up to 50 lbs doesn\'t count against encumbrance while worn properly.', kv: 5 }],
    kv: 6, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Two-Person Tent', itemType: 'misc',
    description: 'Four poles and a promise against the sky.',
    primaryMaterial: 'Nylon', subordinateMaterials: ['Aluminum'], materialClass: 'Soft',
    weightLbs: 5, rarity: 1,
    itemAbilities: [{ name: 'Shelter', description: 'Permits full rest outdoors; negates weather penalties for sleep in non-extreme conditions.', kv: 3 }],
    kv: 4, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Camp Stove', itemType: 'tool',
    description: 'A pocket kitchen that runs on little green cans.',
    primaryMaterial: 'Steel', materialClass: 'Hard',
    weightLbs: 1, rarity: 1,
    itemAbilities: [{ name: 'Hot Food Anywhere', description: 'Cooking in the field without fire-building checks.', kv: 1 }],
    kv: 2, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Water Filter (Pump)', itemType: 'tool',
    description: 'Turns questionable creeks into drinking water, one squeeze at a time.',
    primaryMaterial: 'Polymer', materialClass: 'Hard',
    weightLbs: 1, rarity: 2,
    itemAbilities: [{ name: 'Clean Water', description: 'Renders any freshwater source safe; removes water-sourcing survival checks.', kv: 3 }],
    kv: 4, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Binoculars (10x42)', itemType: 'tool',
    description: 'Distance, negotiated down by a factor of ten.',
    primaryMaterial: 'Polymer', subordinateMaterials: ['Glass'], materialClass: 'Hard',
    weightLbs: 1.5, rarity: 1,
    itemAbilities: [{ name: 'Long Sight', description: 'Visual observation at distance carries no range penalty.', kv: 3 }],
    kv: 4, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Multitool', itemType: 'tool',
    description: 'Seventeen tools folded into one pocket-sized compromise.',
    primaryMaterial: 'Stainless Steel', materialClass: 'Hard',
    weightLbs: 0.5, rarity: 1,
    itemAbilities: [{ name: 'Improvise', description: 'Counts as basic tools for field repairs; such checks avoid the no-tools penalty.', kv: 3 }],
    kv: 4, tags: ['tool', 'outdoor', 'modern'],
  },
  {
    name: 'Paracord (100ft)', itemType: 'consumable',
    description: 'A hundred feet of yes-you-can.',
    primaryMaterial: 'Nylon', materialClass: 'Soft',
    weightLbs: 0.7, rarity: 1, properties: ['Strong', 'Flexible'],
    kv: 1, tags: ['outdoor', 'modern'],
  },
  {
    name: 'Bear Spray', itemType: 'consumable',
    description: 'Concentrated regret, thirty-foot range, one use.',
    primaryMaterial: 'Aluminum', materialClass: 'Hard',
    weightLbs: 0.8, rarity: 2,
    damage: { decay: 6 }, range: 'short', targetAttribute: 'focus',
    itemAbilities: [{ name: 'Deterrent Cloud', description: 'Target (beast or person) must pass DR7 Constitution or disengage, blinded −3 for the scene. Single use.', kv: 4 }],
    kv: 11, tags: ['outdoor', 'defense', 'modern'],
  },

  // ── Office & misc ──
  {
    name: 'Notebook & Pen', itemType: 'misc',
    description: 'The oldest external memory that never needs charging.',
    primaryMaterial: 'Paper', materialClass: 'Soft',
    weightLbs: 0.5, rarity: 1, properties: ['Flammable'],
    kv: 1, tags: ['office', 'modern'],
  },
  {
    name: 'Briefcase', itemType: 'accessory',
    description: 'A portable office that doubles as a statement.',
    primaryMaterial: 'Leather', subordinateMaterials: ['Aluminum'], materialClass: 'Soft',
    weightLbs: 4, rarity: 1, baseResist: 3,
    kv: 2, tags: ['office', 'modern'],
  },
  {
    name: 'Umbrella', itemType: 'misc',
    description: 'A collapsible ceiling with delusions of swordhood.',
    primaryMaterial: 'Nylon', subordinateMaterials: ['Steel'], materialClass: 'Soft',
    weightLbs: 1, rarity: 1,
    kv: 1, tags: ['household', 'modern'],
  },
  {
    name: 'Skateboard', itemType: 'misc',
    description: 'Seven plies of maple and total commitment.',
    primaryMaterial: 'Maple', subordinateMaterials: ['Steel'], materialClass: 'Hard',
    weightLbs: 8, rarity: 1,
    itemAbilities: [{ name: 'Roll', description: 'On pavement, move at double walking pace (Athletics for tricks and speed).', kv: 2 }],
    kv: 3, tags: ['transport', 'modern'],
  },
];
