/**
 * Modern-Earth Nectars — permanent positive exploits, everyday-life flavored.
 *
 * Play-defining bar (canon): "would removing this make the character feel
 * meaningfully different?" Flat bonuses only as one clause inside a larger
 * mechanic. KV anchors: +1 flat ≈ 5 KV, contextual less; First-Born = +50.
 */

import type { TraitTemplate } from './types';

export const MODERN_NECTARS: TraitTemplate[] = [
  {
    name: 'Photographic Memory',
    type: 'nectar',
    pillar: 'soul',
    category: 'learning',
    description: 'The bearer\'s mind keeps the receipts. All of them.',
    mechanicalEffect: 'Once per scene, the bearer may have the GM restate verbatim any detail the bearer personally witnessed this session. Recall checks gain +2.',
    rollModifiers: [{ flat: 2, skillNamePattern: 'research', label: 'Photographic Memory' }],
    kv: 40,
    tags: ['modern'],
  },
  {
    name: 'Perfect Pitch',
    type: 'nectar',
    pillar: 'soul',
    category: 'art',
    description: 'Every sound arrives labeled.',
    mechanicalEffect: 'The bearer identifies any note, key, or familiar voice without a check. Music checks gain +2. Once per scene, the bearer may notice an audio detail everyone else missed (GM provides it).',
    kv: 20,
    tags: ['modern'],
  },
  {
    name: 'Silver Tongue',
    type: 'nectar',
    pillar: 'soul',
    category: 'social',
    description: 'Words queue up for the bearer in their best order, wearing their best clothes.',
    mechanicalEffect: 'Social checks gain +1. Once per session, the bearer may reroll a failed persuasion attempt by genuinely changing tactics (new angle, new offer — player describes it).',
    rollModifiers: [{ flat: 1, skillNamePattern: 'persua', label: 'Silver Tongue' }],
    kv: 30,
    tags: ['modern'],
  },
  {
    name: 'Steady Hands',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'Coffee, adrenaline, gunfire — the hands do not care. The hands are busy.',
    mechanicalEffect: 'Fine-motor checks (surgery, lockwork, soldering, defusing) gain +2, and stress or time pressure never adds penalties to them for the bearer.',
    kv: 30,
    tags: ['modern'],
  },
  {
    name: 'Iron Stomach',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'The bearer\'s digestion has seen things and no longer asks questions.',
    mechanicalEffect: 'The bearer is immune to food-borne illness and gains +2 on checks against ingested toxins. Questionable street food is always safe (and usually delicious).',
    kv: 10,
    tags: ['modern'],
  },
  {
    name: 'Green Thumb',
    type: 'nectar',
    pillar: 'spirit',
    category: 'utility',
    description: 'Things grow for the bearer. Ask the tomatoes; they will not shut up about it.',
    mechanicalEffect: 'Plant-related checks gain +2. Once per session, something the bearer tended earlier bears literal or figurative fruit (GM decides the form; it is always genuinely useful).',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Human Calculator',
    type: 'nectar',
    pillar: 'soul',
    category: 'learning',
    description: 'Numbers resolve themselves in the bearer\'s head, politely and instantly.',
    mechanicalEffect: 'Mental math, estimation, and odds are instant and exact — no check. Checks that hinge on rapid numeric insight (counting cards, spotting a rigged ledger) gain +2.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Polyglot Ear',
    type: 'nectar',
    pillar: 'soul',
    category: 'learning',
    description: 'Languages unlock for the bearer like puzzles that want to be solved.',
    mechanicalEffect: 'After one scene of immersion in an unfamiliar language, the bearer can manage basic phrases. Language-learning between sessions is twice as fast. Accent-reading checks gain +2.',
    kv: 20,
    tags: ['modern'],
  },
  {
    name: 'Night Owl',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'The bearer\'s hours begin where everyone else\'s end.',
    mechanicalEffect: 'Between midnight and dawn, the bearer\'s checks gain +1 and they never suffer drowsiness penalties. (Mornings are not this Nectar\'s problem.)',
    kv: 10,
    tags: ['modern'],
  },
  {
    name: 'Early Riser',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'Dawn finds the bearer already moving, insufferably cheerful about it.',
    mechanicalEffect: 'From dawn to noon, the bearer\'s checks gain +1. The bearer always wakes exactly when they intend to, without an alarm.',
    kv: 10,
    tags: ['modern'],
  },
  {
    name: 'Pack Mule',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'One trip. It is always one trip.',
    mechanicalEffect: 'The bearer\'s carrying capacity is (Clout + 3) × 10 lbs instead of Clout × 10. Carrying a heavy load never slows the group\'s travel pace because of the bearer.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Runner\'s Lungs',
    type: 'nectar',
    pillar: 'body',
    category: 'athletics',
    description: 'Distance is a negotiation, and the bearer always has the better lawyer.',
    mechanicalEffect: 'Sprinting and sustained exertion never trigger exhaustion checks for the bearer. Chase and pursuit checks gain +2.',
    kv: 20,
    tags: ['modern'],
  },
  {
    name: 'People Person',
    type: 'nectar',
    pillar: 'soul',
    category: 'social',
    description: 'Strangers tell the bearer things they have not told their families.',
    mechanicalEffect: 'First-impression checks gain +2, and strangers default one step friendlier toward the bearer. Once per session, an acquaintance offers a small unprompted favor.',
    kv: 25,
    tags: ['modern'],
  },
  {
    name: 'Mechanical Intuition',
    type: 'nectar',
    pillar: 'spirit',
    category: 'utility',
    description: 'Machines confess to the bearer. A rattle, a smell, a hesitation — it all testifies.',
    mechanicalEffect: 'Once per scene, the bearer may ask the GM what is wrong with a machine and get a true, useful answer. Repair checks gain +2.',
    kv: 25,
    tags: ['modern'],
  },
  {
    name: 'Cat Napper',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'Any chair, any floor, any parked car: ten minutes, gone, back, better.',
    mechanicalEffect: 'The bearer can take a Short Rest in ten minutes in any tolerably safe place, and cannot be penalized for interrupted sleep.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Unshakeable',
    type: 'nectar',
    pillar: 'soul',
    category: 'resolve',
    description: 'Panic arrives, checks the bearer\'s face, and quietly leaves.',
    mechanicalEffect: 'Fear and intimidation effects on the bearer step down one severity. Checks to steady others gain +2, and the bearer\'s calm is contagious: allies in reach may reroll one fear check per scene.',
    rollModifiers: [{ flat: 1, governorAttribute: 'willpower', label: 'Unshakeable' }],
    kv: 35,
    tags: ['modern'],
  },
];
