/**
 * Modern-Earth Thorns — long-term conditions (mental health + physical).
 *
 * Mike ruling 2026-08-04: mental-health issues and real physical
 * disabilities/illnesses are legitimate Thorns; maturity flags handle
 * audience, not content avoidance. Short-term illness = negative Blossom
 * (see blossoms.ts), long-term = Thorn.
 *
 * Design bar for this file:
 * - The mechanic models the FUNCTIONAL lived impact, never a caricature.
 *   No forced roleplay, no "roll to act irrationally" — the bearer's
 *   player always keeps authorship of who they are.
 * - Easy-to-track triggers only: binary states, player-declared steps,
 *   once-per-session GM declarations, pool-at-0.
 * - Liens are graded against the anchors: −15 mild nuisance, −30 daily
 *   management, −50 shapes most scenes, −90+ reshapes how the character
 *   plays entirely. (Diminishing = −200 is the severe ceiling reference.)
 * - Several thorns pair with items in items.ts (Inhaler, EpiPen, Insulin,
 *   Wheelchair, Glasses) — the item is the counterplay, which keeps the
 *   thorn honest without making it unplayable.
 *
 * Deliberately NOT in this pass (need Mike's read before authoring):
 * eating disorders, tic disorders, substance-use disorder (Addictions
 * system is CUT — a thorn here might tread on it), personality disorders.
 */

import type { TraitTemplate } from './types';

export const MENTAL_HEALTH_THORNS: TraitTemplate[] = [
  {
    name: 'Major Depression',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'A weight that arrives without reason and leaves without permission. Some mornings the world is gray glass, and everything worth doing sits on the far side of it.',
    mechanicalEffect: 'Short Rests restore the bearer 1 less than normal (min 0). Once per session the GM may declare a Gray Day at scene start: −1 to all the bearer\'s checks until they succeed on any check that scene.',
    kv: -45,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Generalized Anxiety',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'The mind rehearses catastrophes with professional thoroughness. It is never off the clock.',
    mechanicalEffect: 'The bearer\'s first check in any scene takes −2 unless they first spend 1 Effort steadying themselves (declared, costs no action).',
    kv: -30,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Panic Attacks',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Sometimes the alarm goes off and nothing is on fire. The body does not care about the difference.',
    mechanicalEffect: 'When the bearer\'s Willpower current hits 0, they are also Muted (cannot add Effort) until the scene ends or another character spends an action grounding them.',
    kv: -35,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'PTSD',
    type: 'thorn',
    pillar: 'spirit',
    category: 'mental-health',
    description: 'The past does not stay where it was left. Certain doors open on their own.',
    mechanicalEffect: 'Choose a Trigger with the GM at attachment. In any scene where the Trigger is present, the bearer\'s first check takes −3 and they may wager at most 1 Effort that scene. Leaving the scene clears both immediately.',
    kv: -50,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'ADHD',
    type: 'thorn',
    pillar: 'spirit',
    category: 'mental-health',
    description: 'Forty tabs open, and the important one is silent. Then, without warning, one tab becomes the entire world.',
    mechanicalEffect: 'Repeating the same action as the bearer\'s previous round requires a DR5 Fate-Die check first; on a fail the action still happens at −2. Once per session, acting on a brand-new problem, the bearer gains +2 (hyperfocus).',
    kv: -25,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'OCD',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Order is safety; the ritual is the lock on the door. The lock must be checked. It must be checked again.',
    mechanicalEffect: 'Define a Ritual with the GM at attachment. The bearer\'s first check in a high-stakes scene takes −2 unless the Ritual was performed this scene. If someone interrupts the Ritual, the bearer loses their next action.',
    kv: -30,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Social Anxiety',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Every room has a spotlight, and it is always on. Everyone else got the script in advance.',
    mechanicalEffect: 'Social checks with three or more strangers present take −2. Once per scene the bearer may step back (forfeiting their next action) to clear the penalty for the rest of the scene.',
    kv: -25,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Bipolar Disorder',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'The tide comes in high or goes out far; it rarely rests at shore.',
    mechanicalEffect: 'At session start, roll the bearer\'s Fate Die. Max value = Ascent: +1 effect on every Effort spend, but the bearer must wager Effort whenever able. A 1 = Trough: every Effort spend costs 1 extra. Anything else = Level. The roll cannot be overridden.',
    kv: -50,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Dyslexia',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Letters trade places when nobody is watching. The words are all there — the order is negotiable.',
    mechanicalEffect: 'Checks that hinge on reading or writing under time pressure take −3. With double time or someone reading aloud, no penalty. Purely verbal equivalents are unaffected.',
    kv: -15,
    tags: ['mental-health', 'modern', 'learning'],
  },
  {
    name: 'Chronic Insomnia',
    type: 'thorn',
    pillar: 'body',
    category: 'mental-health',
    description: 'Sleep is a country that keeps refusing the visa.',
    mechanicalEffect: 'When the bearer takes a Short Rest, roll their Fate Die: on a 1, it restores nothing. A full night of safe sleep always works.',
    kv: -20,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Claustrophobia',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Small spaces have teeth. The walls do not move, which is exactly what they want you to think.',
    mechanicalEffect: 'On entering a confined space, DR5 Willpower Fate-Die check; on a fail, −2 to all checks while confined. The bearer may retry once after a full round of steadying.',
    kv: -20,
    tags: ['mental-health', 'modern', 'phobia'],
  },
  {
    name: 'Agoraphobia',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Open ground, open crowds, no walls to put your back against. Home is the only room that never watches back.',
    mechanicalEffect: 'On entering a wide-open or heavily crowded space, DR5 Willpower Fate-Die check; on a fail, −2 to all checks while exposed. The bearer may retry once after a full round of steadying.',
    kv: -20,
    tags: ['mental-health', 'modern', 'phobia'],
  },
  {
    name: 'Chronic Nightmares',
    type: 'thorn',
    pillar: 'spirit',
    category: 'mental-health',
    description: 'Sleep arrives, but it brings work.',
    mechanicalEffect: 'After any scene that touched the bearer\'s old wounds (binary, GM call), their next rest restores 1 less than normal (min 0).',
    kv: -15,
    tags: ['mental-health', 'modern'],
  },
];

export const PHYSICAL_THORNS: TraitTemplate[] = [
  {
    name: 'Severely Nearsighted',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The world past arm\'s reach is watercolor.',
    mechanicalEffect: 'Without corrective lenses, checks relying on distance vision take −3. With glasses or contacts (item), no penalty — but now there is a thing that can be lost or broken.',
    kv: -10,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Blind in One Eye',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Half the world arrives on a delay, reported secondhand by the other half.',
    mechanicalEffect: 'Checks requiring depth perception or covering the blind-side periphery take −2. Ranged attacks take −1.',
    kv: -20,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Blind',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Sight is a rumor other people insist on. The world is texture, weight, echo, and warmth — and it is still the world.',
    mechanicalEffect: 'Sight-dependent checks automatically fail. Acting through other senses takes −3, except in spaces the bearer knows well (no penalty). Ranged attacks beyond touch are impossible.',
    kv: -110,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Deaf',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The world runs on a soundtrack the bearer was never sent. People forget how much they say without looking.',
    mechanicalEffect: 'Hearing-dependent checks automatically fail. Group coordination checks take −2 unless sightline signals were arranged this scene (declared once, free).',
    kv: -70,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Hard of Hearing',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Conversations arrive with gaps the mind quietly fills — usually correctly.',
    mechanicalEffect: 'Hearing-dependent checks take −2. In loud environments, spoken coordination with the bearer requires facing them (binary).',
    kv: -20,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Asthma',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The lungs keep their own ledger, and sprinting is an expensive line item.',
    mechanicalEffect: 'After all-out physical exertion (binary, GM call), DR5 Constitution Fate-Die check; on a fail, −2 to Body checks until the bearer skips one action to recover breath. Using an Inhaler (item) clears it instantly.',
    kv: -25,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Chronic Pain',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Pain is weather: some days a drizzle, some days a storm — always a sky.',
    mechanicalEffect: 'The bearer\'s first Body-pillar check each session takes −2. Once per session the GM may declare a Flare: −2 to all Body checks for that scene.',
    kv: -40,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Type 1 Diabetes',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The body forgot how to do one quiet, constant thing, so the bearer does it manually, every day, forever.',
    mechanicalEffect: 'Requires 1 dose of insulin (item) per in-game day. After a missed day: rests restore nothing and Body checks take −2 until dosed.',
    kv: -30,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Epilepsy',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Somewhere in the wiring there is a switch that throws itself.',
    mechanicalEffect: 'On exposure to a declared trigger (strobe, shock — binary, GM call), DR5 Constitution Fate-Die check; on a fail, the bearer loses their next action and falls prone. After any failure, immune for the rest of the session.',
    kv: -40,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Missing Hand',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The hand is gone; the reaching for it is not.',
    mechanicalEffect: 'Actions assuming two hands are impossible without a prosthetic (item), assistance, or improvisation at −3. One-handed actions are unaffected.',
    kv: -55,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Paraplegia',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The legs stopped answering. The rest of the bearer never did.',
    mechanicalEffect: 'Unassisted walking is impossible. With a wheelchair (item), normal movement on accessible ground; stairs and rough terrain need assistance or a route. Upper-body actions are unaffected.',
    kv: -90,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Severe Allergy',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The immune system has declared war on something harmless, and it does not take prisoners.',
    mechanicalEffect: 'Declare an allergen at attachment. While it is present nearby: −1 to all checks. On direct ingestion or contact: 3 Constitution damage and −2 to Body checks until treated (an EpiPen (item) ends it immediately).',
    kv: -20,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Heart Condition',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The engine runs, but the manufacturer\'s warranty is void.',
    mechanicalEffect: 'After all-out exertion (binary, GM call), DR7 Constitution Fate-Die check; on a fail, take 2 Constitution damage. The bearer knows their limits: they may always refuse exertion without a check or social penalty.',
    kv: -45,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Chronic Fatigue',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Energy is a prepaid account with no overdraft, and the fees are brutal.',
    mechanicalEffect: 'After the bearer\'s third scene of active participation each in-game day, −1 to all checks until they rest.',
    kv: -40,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Chronic Migraines',
    type: 'thorn',
    pillar: 'soul',
    category: 'physical',
    description: 'A private thunderstorm, scheduled by no one, cancelled by nothing.',
    mechanicalEffect: 'Once per session, in a bright, loud, or high-stress scene, the GM may declare onset: −2 to Soul-pillar checks that scene, or the bearer retreats somewhere dark and quiet to clear it.',
    kv: -25,
    tags: ['physical', 'modern'],
  },
];

export const ALL_THORNS: TraitTemplate[] = [...MENTAL_HEALTH_THORNS, ...PHYSICAL_THORNS];
