/**
 * Modern-Earth traits — WAVE 2 (2026-08-04, Mike: "go with wave 2").
 *
 * Includes the previously-deferred eating-disorder and tic-disorder thorns
 * under Mike's ruling (mental health issues are thorns; maturity flags
 * handle audience). Same bar as wave 1: mechanics model the FUNCTIONAL
 * lived impact, never caricature; the player keeps authorship; community
 * and treatment are counterplay wherever true to life.
 *
 * STILL HELD: substance-use disorder — collides with the CUT Values/
 * Addictions system; needs an explicit Mike ruling before authoring.
 */

import type { TraitTemplate } from './types';

export const WAVE2_THORNS: TraitTemplate[] = [
  {
    name: 'Anorexia Nervosa',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'A voice that audits every plate and calls the shrinking discipline. Meals are negotiations the bearer attends alone — unless someone sits down.',
    mechanicalEffect: 'Each morning, a private DR5 Willpower Fate-Die check; on a fail the bearer doesn\'t eat enough today: −2 Body checks and rests restore 1 less until tomorrow. Sharing a meal with a trusted character grants +2 on the check.',
    kv: -45,
    tags: ['mental-health', 'modern', 'mature'],
  },
  {
    name: 'Bulimia Nervosa',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'A cycle that promises control and delivers its opposite, conducted in private and covered with practiced ease.',
    mechanicalEffect: 'After a scene of acute stress or public failure (binary, GM), DR5 Willpower check; on a fail the bearer loses their next scene\'s opening action to the cycle and takes 1 Constitution damage. Others notice only with Insight vs. their cover.',
    kv: -40,
    tags: ['mental-health', 'modern', 'mature'],
  },
  {
    name: 'Tourette Syndrome',
    type: 'thorn',
    pillar: 'body',
    category: 'mental-health',
    description: 'The body has opinions it announces on its own schedule. Suppressing them is real, tiring work that nobody watching ever counts.',
    mechanicalEffect: 'Tics surface under stress. In high-stakes social scenes the bearer either lets them show (−1 on the scene\'s first social check with strangers; none among familiar company) or spends 1 Effort that scene suppressing them.',
    kv: -20,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Misophonia',
    type: 'thorn',
    pillar: 'spirit',
    category: 'mental-health',
    description: 'Certain sounds are not sounds; they are alarms wired straight to the spine.',
    mechanicalEffect: 'Declare two trigger sounds at attachment. While one is present and ongoing (binary), Focus-governed checks take −2 until it stops or the bearer leaves or blocks it (earbuds count).',
    kv: -15,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Face Blindness',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'Faces slide off memory like rain off glass. The bearer knows people by voice, gait, jacket, context — and dreads the word "remember me?"',
    mechanicalEffect: 'The bearer cannot recognize anyone by face alone. Out of expected context, recognition needs a DR5 Wit check. Allies may establish identifying signals (declared once, free).',
    kv: -25,
    tags: ['mental-health', 'modern'],
  },
  {
    name: 'Color Blindness (Red-Green)',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Two of the world\'s favorite signal colors arrive wearing the same coat.',
    mechanicalEffect: 'Checks that hinge on red-green color cues take −3 or require a workaround (labels, an ally, an app).',
    kv: -10,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Tinnitus',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'Silence was discontinued years ago; a thin electric ring plays in its place.',
    mechanicalEffect: 'In quiet environments, hearing checks take −2 — silence is when it is loudest. The bearer never benefits from "total quiet" conditions for listening.',
    kv: -15,
    tags: ['physical', 'modern', 'sensory'],
  },
  {
    name: 'Vertigo',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'The inner ear files false motion reports, and heights countersign them.',
    mechanicalEffect: 'On first exposure each scene to heights, ledges, ladders, or open drops: DR5 Constitution check or −2 to all checks while elevated.',
    kv: -25,
    tags: ['physical', 'modern'],
  },
  {
    name: 'Needle Phobia',
    type: 'thorn',
    pillar: 'soul',
    category: 'mental-health',
    description: 'A small, sharp, completely rational object that the whole nervous system has voted against.',
    mechanicalEffect: 'Injections and blood draws require a DR5 Willpower check; on a fail the procedure needs restraint, help, or a second attempt. Medical scenes involving needles: −2 to the bearer\'s checks until it\'s over.',
    kv: -10,
    tags: ['mental-health', 'modern', 'phobia'],
  },
  {
    name: 'Irritable Bowel',
    type: 'thorn',
    pillar: 'body',
    category: 'physical',
    description: 'A digestive system that treats rich food and bad news as the same emergency.',
    mechanicalEffect: 'After rich food or acute stress (binary, GM), once per session the GM may declare urgency: the bearer must excuse themselves within the scene or take −2 to all checks until they do.',
    kv: -15,
    tags: ['physical', 'modern'],
  },
];

export const WAVE2_NECTARS: TraitTemplate[] = [
  {
    name: 'Ambidextrous',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'Left, right — the hands never learned there was supposed to be a difference.',
    mechanicalEffect: 'No off-hand penalties ever apply. Once per scene, the bearer may perform two simple one-handed actions as a single action.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Perfect Balance',
    type: 'nectar',
    pillar: 'body',
    category: 'athletics',
    description: 'Rails, ledges, and boat decks read as sidewalks.',
    mechanicalEffect: 'No balance checks on narrow or unstable footing under calm conditions; +2 when contested or under fire.',
    kv: 20,
    tags: ['modern'],
  },
  {
    name: 'Lucid Dreamer',
    type: 'nectar',
    pillar: 'spirit',
    category: 'utility',
    description: 'Sleep is a second office with better lighting.',
    mechanicalEffect: 'Once per session, sleep on a problem to receive a true, useful hint from the GM. Nightmare-based rest disruption never affects the bearer.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Map Mind',
    type: 'nectar',
    pillar: 'soul',
    category: 'utility',
    description: 'Every route ever walked is filed, cross-referenced, and open for consultation.',
    mechanicalEffect: 'Routes the bearer has traveled are recalled perfectly — no checks to retrace. Urban navigation checks gain +2.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Trivia Machine',
    type: 'nectar',
    pillar: 'soul',
    category: 'learning',
    description: 'A head full of footnotes, indexed by no discernible system, retrieved at exactly the right moment.',
    mechanicalEffect: 'Once per scene, the bearer may ask the GM for one true, obscure, relevant fact the bearer once read. It is always at least a little useful.',
    kv: 15,
    tags: ['modern'],
  },
  {
    name: 'Sommelier\'s Palate',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'The tongue is a lab. One taste files a report.',
    mechanicalEffect: 'Identify ingredients, provenance, or contamination (drugs, poison, spoilage) in anything tasted at a safe dose with a DR5 check. Food-and-drink social checks gain +2.',
    kv: 10,
    tags: ['modern'],
  },
  {
    name: 'Natural Teacher',
    type: 'nectar',
    pillar: 'soul',
    category: 'social',
    description: 'The bearer explains things and they stay explained.',
    mechanicalEffect: 'Once per session, coach a present ally through a task: they gain +2 on one check using any skill the bearer has at d6 or better.',
    kv: 25,
    tags: ['modern'],
  },
  {
    name: 'Fast Metabolism',
    type: 'nectar',
    pillar: 'body',
    category: 'utility',
    description: 'A furnace where most people keep a stove. Runs hot, runs hungry.',
    mechanicalEffect: 'Short Rests restore the bearer 1 extra. Skip a full day of food and the benefit is gone until properly fed.',
    kv: 10,
    tags: ['modern'],
  },
  {
    name: 'Handy',
    type: 'nectar',
    pillar: 'spirit',
    category: 'utility',
    description: 'The bearer has done a bit of everything, and the hands remember most of it.',
    mechanicalEffect: 'Once per session, attempt any practical trade task (repair, build, rig, patch) as if trained: flat +2 instead of unskilled.',
    kv: 20,
    tags: ['modern'],
  },
];

export const WAVE2_BLOSSOMS: TraitTemplate[] = [
  // Negative — short-term states
  {
    name: 'Hangover',
    type: 'blossom',
    pillar: 'body',
    category: 'illness',
    description: 'Last night, itemized, with interest.',
    mechanicalEffect: '−1 to all checks; −2 in bright or loud environments. Clears by midday, or after water, grease, and an hour of mercy.',
    kv: -5,
    tags: ['modern', 'temporary', 'mature'],
  },
  {
    name: 'Sunburn',
    type: 'blossom',
    pillar: 'body',
    category: 'injury',
    description: 'The sun sent an invoice and the skin is paying in installments.',
    mechanicalEffect: '−1 to Body checks; any firm contact with burned skin costs an additional −1 that round. Clears in two days.',
    kv: -5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Blisters',
    type: 'blossom',
    pillar: 'body',
    category: 'injury',
    description: 'New boots, old story.',
    mechanicalEffect: 'Travel pace halves and movement-heavy checks take −1. Clears after a day off the feet or proper dressing (First Aid).',
    kv: -5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Seasonal Allergies',
    type: 'blossom',
    pillar: 'body',
    category: 'illness',
    description: 'The trees are doing something unspeakable and the sinuses have opinions.',
    mechanicalEffect: 'Outdoors in season: −1 to perception checks, and on a Fate-Die 1 during stealth, a sneeze gives the bearer away. Antihistamines (item) suppress it for a day.',
    kv: -5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Toothache',
    type: 'blossom',
    pillar: 'body',
    category: 'illness',
    description: 'A very small place demanding a very large share of attention.',
    mechanicalEffect: '−1 to concentration checks. Eating anything hard: DR5 Constitution or −2 for the scene. Ends with dental care, not hope.',
    kv: -5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Stiff Neck',
    type: 'blossom',
    pillar: 'body',
    category: 'injury',
    description: 'Slept wrong; turning right is now a full-body decision.',
    mechanicalEffect: 'Awareness checks for things behind the bearer take −2; sudden dodges take −1. Clears in a day.',
    kv: -5,
    tags: ['modern', 'temporary'],
  },
  // Positive — earned moments
  {
    name: 'Fresh Start',
    type: 'blossom',
    pillar: 'soul',
    category: 'boost',
    description: 'Haircut, clean clothes, shoes that mean it.',
    mechanicalEffect: '+1 to first-impression and confidence checks. Ends after the next genuinely hard scene, or a rainstorm.',
    kv: 5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Crowd Energy',
    type: 'blossom',
    pillar: 'spirit',
    category: 'boost',
    description: 'The room is warm and it is rooting for you.',
    mechanicalEffect: 'While performing for a receptive audience: +2 to performance checks this scene.',
    kv: 5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Beginner\'s Luck',
    type: 'blossom',
    pillar: 'spirit',
    category: 'boost',
    description: 'The universe subsidizes first attempts.',
    mechanicalEffect: 'GM bestows. The bearer\'s first-ever attempt at one unfamiliar skill this session gains +2.',
    kv: 5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Runner\'s High',
    type: 'blossom',
    pillar: 'body',
    category: 'boost',
    description: 'Endorphins, cashing in.',
    mechanicalEffect: 'After real exercise: +1 to Soul-pillar checks for the following scene.',
    kv: 5,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Good News Day',
    type: 'blossom',
    pillar: 'soul',
    category: 'boost',
    description: 'Something finally landed right, and the whole day tilts with it.',
    mechanicalEffect: 'After genuinely good personal news (GM bestows): +1 to all checks for the rest of the scene, and the bearer\'s optimism can\'t be turned against them by fear effects this scene.',
    kv: 10,
    tags: ['modern', 'temporary'],
  },
  {
    name: 'Sugar Rush',
    type: 'blossom',
    pillar: 'body',
    category: 'boost',
    description: 'Birthday-cake physics: fast now, floor later.',
    mechanicalEffect: '+1 to Celerity-governed checks this scene; −1 to all checks the following scene (the crash).',
    kv: 0,
    tags: ['modern', 'temporary'],
  },
];

export const WAVE2_TRAITS: TraitTemplate[] = [...WAVE2_THORNS, ...WAVE2_NECTARS, ...WAVE2_BLOSSOMS];
